### Get Current User

GET http://localhost:5000/api/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI0MGQwZjVkYy0wZWZkLTQwN2MtYWVlOS04NTBkM2NlYmI5MTgiLCJpYXQiOjE3ODE4NjI5NTMsImV4cCI6MTc4MjQ2Nzc1M30.V6DRSFZzXGZBUaywAevMfkLQo4NsWYpGgERfsmPuplY


### No Token

GET http://localhost:5000/api/user